name: varfish-db-downloader
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- python =3.9
- snakemake =7.8
- bedops ==2.4.35
- bcftools =1.15
- htslib =1.15
- samtools =1.15
- drmaa ==0.7.9
- bedtools ==2.27.1
- var-agg ==0.1.1
- lftp
- varfish-annotator-cli ==0.16
- jannovar-cli
- snakefmt
