name: varfish-db-downloader
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake-minimal =7
  - bedops =2
  - bcftools =1.15
  - htslib =1.16
  - samtools =1.16
  - bedtools =2.30
  - var-agg ==0.1.1
  - lftp
  - interval-binning =1
  - vcfpy
  - tqdm
  - prov =2
  - jq
  - aria2
  - pigz
  # Elementary Python dependencies
  - python =3.10
  - setuptools-scm
  - attrs
  - cattrs
  - click
  - loguru
  - pyyaml
  - requests
  - requests-ftp
  # Python and Snakemake formatting and linting.
  - black >=23.0,<24.0
  - snakefmt >=0.8,<0.9
  - isort >=5.0,<6.0
  - flake8 >=6.0,<7.0
  # Shell formatting and linting.
  - beautysh >=6.0,<7.0
  - shellcheck >=0.9,<0.10
