name: varfish-db-downloader
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Python and Python packages.
  - python =3.10
  - setuptools-scm
  - attrs
  - cattrs
  - click
  - loguru
  - pyyaml
  - requests
  - requests-ftp
  - snakemake-minimal =7
  - interval-binning >=1.0,<2.0
  - tqdm
  - vcfpy
  # Python and Snakemake formatting and linting.
  - black >=23.0,<24.0
  - snakefmt >=0.8,<0.9
  - isort >=5.0,<6.0
  - flake8 >=6.0,<7.0
  # Shell formatting and linting.
  - beautysh >=6.0,<7.0
  - shellcheck >=0.9,<0.10
  # JSON transformation tool used in many rules.
  - jq
  # Tools for file downloads.
  - aria2
  - wget
  # Tool for processing BED files.
  - bedops =2
  # VCF/BCF/HTSlib/Samtools.
  - bcftools =1.15
  - htslib =1.16
  - samtools =1.16
  # Parallel (de)compression.
  - pigz
