#!/usr/bin/bash

# This is a stub for aria2c.  By placing its parent directory at the front of
# the PATH, we can ensure that the real wget is not used during tests.

varfish-db-downloader wget run-stub-aria2c "$@"
